### PR TITLE
Change 'id' filter.

### PR DESCRIPTION
**Pull request by prockallsyms**
IDK lulz

### CODE REVIEW

**Comment by 0x6C77** [comment]
What is the purpose of this commit?

**Comment by Dom-1** [comment]
To improve the filtering function on the value of 'id'.

**Comment by 0x6C77** [comment]
How is this improving the filtering?

**Comment by Dom-1** [comment]
I was reading some articles online over PHP filtering and when the code is changed, filtering can be more deliberate with less 0days or bugs resulting from input.

**Comment by verath** [comment]
I think the difference is filtering what we don't want, versus extracting only what we want? Current implementation removes everything but numbers, Dom-1's alternative extracts only numbers from the string. The result should not be any different. IMO the current implementation is easier to understand.

Anyhow, if one really wanted to "improve" the filtering, perhaps a more explicit solution would be using [filter_var](http://php.net/manual/en/function.filter-var.php) with the `FILTER_SANITIZE_NUMBER_INT` flag?

**Comment by Dom-1** [comment]
Damn @verath , you took the words right out of my mouth. I was just testing it locally to see if it would be faster this way ^^
Of course I do like that filter_var idea. Never seen that before but I'll take a look ;)

**Pull request closed without merging**
