### PR TITLE
Fix installation script for Ubuntu

### PR DESCRIPTION
**Pull request by tehron**
The installation script didn't finish successfully on Ubuntu 16.04 LTS (amd64) until the following fixes were applied.

### CODE REVIEW

**Comment by 0x6C77** [comment]
I don't think most of these changes are necessary.
- Both php and php5 packages should be available and I am more comfortable specify the version
- `DEFAULT CURRENT_TIMESTAMP` is only allowed on one column per table in MySQL 5.6.5+ so again I would like to leave this as is. The other columns are handled by the insert/update scripts anyway.
- `a2enmod rewrite` - looks like a good edition though

What errors were you having before you added these changes?

**Comment by tehron** [comment]
I did a fresh installation of the latest Ubuntu.
* I got an error when using php5

> tehron@ubuntu:~/flabby/hackthis.co.uk$ sudo apt-get install php5
[sudo] password for tehron:
Reading package lists... Done
Building dependency tree
Reading state information... Done
Package php5 is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

> E: Package 'php5' has no installation candidate

* Without these default values added, there was the following error:

> tehron@ubuntu:~/flabby/hackthis.co.uk$ mysql -u root -p < sql/schema.sql
Enter password:
ERROR 1067 (42000) at line 32: Invalid default value for 'completed'

Using `mysqld 5.7.12-0ubuntu1.1`

**Comment by 0x6C77** [comment]
Are you using Ubuntu 16.04? Looks like they dropped the php5 package from the repository.

Also could you try changing the timestamp lines to `TIMESTAMP NULL DEFAULT NULL` and see if that fixes your issue?

**Comment by tehron** [comment]
Ubuntu 16.04, yes. And yes, php5 has been removed for php7. See [http://askubuntu.com/questions/756879/cant-install-php5-on-ubuntu-16-04](http://askubuntu.com/questions/756879/cant-install-php5-on-ubuntu-16-04)

With your suggested fix, sql/schema.sql can be fed to mysql successfully.

**Comment by thibmo** [comment]
What you could do, to get php5.6 (I know, awefully specific) anyways, is the following:
**Remove all the stock php packages**
sudo aptitude purge \`dpkg -l | grep php | awk '{print $2}' |tr "\n" " "\`

**Add the PPA**
sudo add-apt-repository ppa:ondrej/php

**Install your PHP Version**
sudo apt-get update
sudo apt-get upgrade
sudo apt-get install php5.6

**You can also install php5.6 modules**
sudo apt-get install php5.6-mbstring php5.6-mcrypt php5.6-mysql php5.6-xml

**Verify your version**
sudo php -v

There is also a way to use another repo with custom build of php5.4 and php5.6 (Including mods), not sure where the link went off to but I lost it. xD

**Pull request closed without merging**
